image: maven:3-openjdk-17

stages:
  - build
  - test
  - compile
  - deploy

build:
  stage: build
  only:
    - master
  script:
    - mvn compile

test:
  stage: test
  only:
    - master
  script:
    - mvn test

compile:
  stage: compile
  only:
    - master
  script:
    - mvn package
  artifacts:
    paths:
      - target/*.jar

deploy:
  stage: deploy
  only:
    - master
  script:
    - cd target
    - ls
